### PR TITLE
Operation/randomize crypt iv

### PR DESCRIPTION
**Pull request by tslotboom**

### CODE REVIEW

**Review by GraceJegede — APPROVED** [review]
I just noticed how pkcs7_padding_data_length() could be typecast to uint32_t
Checking its source file from aes library (pkcs7Pdding.c), I see that the function works with size_t which is kind of cool and helps to make this type casting possible.

**Comment by matthew-buglass** [comment]
Because we are pulling our key from the FRAM, should we be taking the privateKey variable out now, before the PR, or should we do it later, once we start integration testing?

**Comment by tslotboom** [comment]
> Because we are pulling our key from the FRAM, should we be taking the privateKey variable out now, before the PR, or should we do it later, once we start integration testing?

**Comment by tslotboom** [comment]
@matthew-buglass in my opinion leave the private key here until the alternative is known to be working

**Review by matthew-buglass — APPROVED** [review]
Looks good.

**Pull request merged**
