### PR TITLE
Adding ISISpace SDK to our repo, and porting all of our existing code into it

### PR DESCRIPTION
**Pull request by tyrelkostyk**
This PR contains the _first_ official WORKING build of our project's code!! It's currently just a super simple demo project that flickers some LEDs, however it's 100% ready to evolve into much more.

**Key points of this PR:**
- added the radsat-sk/ folder -> this is the eclipse project folder, it must contain all of our code
- added the hal/ folder -> it contains the hardware abstraction library (and a demo), and is required for the radsat-sk project to build
- added the satellite-subsystems/ folder -> it is not included nor is it necessary, however it may be very useful to use as a reference (e.g. how to communicate with the solar panels)
- all of our pre-existing code and directories have been added to the project (including the necessary project settings)
- I #ifdef'd out all of the actual code though, to prevent compiler errors
- I did NOT include the main-application directory or any of its files - it is my strong belief that task definitions and everything high level like that should be kept within main.c, since we'll need to share a lot of globals and other info etc. I'm open to opposing ideas, but I think this is the best path forward
- I have not tested this on any actual hardware yet, however I can confirm that the drivers are ready to go
- I have not tested this on another machine, however I cloned and built the project from a random repo on my PC, and all the includes are relative, so in theory so long as someone runs the SDK installer first, everything should work after simply cloning the repo

**Using the SDK/IDE may take some getting used to.** Feel free to play around with it (and google is your friend), however some things are super obscure, so feel free to reach out to me if you need assistance. For example, when you create or import a new folder, the IDE automatically "ignores" it. So you have to right-click it, go to "Resource Configurations" -> "Exclude from build..." and then deselect all of the build configurations, since they'll be selected (aka excluded) by default.

**To build and use this project,** all anyone has to do is install the SDK, install the JLink drivers, clone the repo, and then open the repo from within their ISISpace Eclipse IDE. Instructions on how to do this will be added to the training doc, and perhaps we can put that information into the readMe as well.

[DropBox Link to the SDK Installer folder](https://www.dropbox.com/home/CubeSat/Subteams/Software%20and%20Command/ISISpace%20SDK%20and%20EIDP/ISISpace%20SDK)

### CODE REVIEW

**Review by rarohel — APPROVED** [review]
Great work! I downloaded this project and it built, so I trust that it's all working.

**Review by jacobwaskowic — CHANGES_REQUESTED** [review]
I believe that we shouldn't have the HAL on the repo, right? Other than that, everything built correctly so it looks good to me.

**Review by MackenzieStanger — APPROVED** [review]
Personally I prefer to break up the tasks and have just the main function in main.c but I can be flexible. I have no other issues looks good to me

**Review by jacobwaskowic — APPROVED** [review]
Now that the HAL is not uploaded to the git, I believe everything should be good to go as before.

**Pull request merged**
