### PR TITLE
updated the Setting Up Your Repo section

### PR DESCRIPTION
**Pull request by MackenzieStanger**
Let me know if this is good enough documentation of what the two commands do

### CODE REVIEW

**Comment by tyrelkostyk** [comment]
That definitely helps, but an extra line above/below these commands saying what githooks are or what they do would be great haha. If I recall correctly, they add checks to make sure branches follow the naming conventions, right?

**Comment by MackenzieStanger** [comment]
Added a description. Take a look and let me know if it is acceptable

**Review by jacobwaskowic — APPROVED** [review]
This makes sense to me. I think it gives a sufficient explanation on what the commands do.

**Review by tyrelkostyk — APPROVED** [review]
Looks good! Approved. You're free to merge and delete the source branch when you're ready, Mackenzie

**Pull request merged**
